### ISSUE TITLE
Unresolved symbol error - HuntMax

### ISSUE THREAD

**Issue by jesjenn** [Lexaron/CellSIM#10]
# Describe the issue: 
Engine.java and Monitor.java have references to a HuntMax cell class, but there is no HuntMax cell class. I keep getting an unresolved symbol 'HuntMax' error.  Is this supposed to be HuntLargest?

# Propose a solution: 
Rename HuntLargest with HuntMax

**Comment by m1rza-s** [comment]
Hello Jesjenn, you're absolutely right. I forgot to commit add the renamed class into the Changelist. Feel free to rename your local HuntLargest to HuntMax, or wait until I finish refactoring the Cell package. :)

Thanks!
