### ISSUE TITLE
TimerTask doesn't stop

### ISSUE THREAD

**Issue by m1rza-s** [Lexaron/CellSIM#2]
TimerTask doesn't stop if the simulation is closed before all cells die. This causes the JVM to stay in the task manager and it locks CellSIM.jar as being used so building is impossible unless you manually close JVM through your IDE or task manager.

**Comment by that1guy232** [comment]
Why not just call System.exit() When you close the window?

**Comment by m1rza-s** [comment]
@that1guy232 , it does solve the issue, but it makes the code unrunnable on some platforms. I kinda wanted to avoid that, but it looks like I'll just have to live with it.
